# 将此文件重命名为xxxx.yaml（其中xxxx可任意拟定）
# 填写前请先查阅说明文档

# 此为该用户的登录方式，可选项如下：
# "SSO" - 统一身份认证登录
# "LOCAL" - 本地登录/校外人员登录
# "MANUAL" - 直接指定cookies登录（仅供专业人士使用）
login_method: "SSO"

# =========== 若登录方式为SSO（统一身份认证登录）或LOCAL（本地登录/校外人员登录），请填写本栏信息 =========== #
# 请将双引号内的值替换为该用户的用户名
username: "3212345678"

# 请将双引号内的值替换为该用户的密码
password: "mypassword"


# =================================================================================================== #

# ====================== 若登录方式为MANUAL（直接指定cookies登录），请填写本栏信息 ======================= #
# 请将双引号中的许多x替换为对应值
cookies:
  session_lims2_cf_cpu: "xxxxxxxxxxxxxxxxxxxxxxxxxx"


# =================================================================================================== #

# 以井号（#）开头的行是注释，不会被程序读取
# 请不要修改每一行的冒号前的内容
# 在每行填写信息时，除非你知道自己在做什么，否则不建议删除双引号，也不要删除冒号和引号之间的空格
